// Generated by gencpp from file robot_actions/move_baseGoal.msg
// DO NOT EDIT!


#ifndef ROBOT_ACTIONS_MESSAGE_MOVE_BASEGOAL_H
#define ROBOT_ACTIONS_MESSAGE_MOVE_BASEGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Point.h>

namespace robot_actions
{
template <class ContainerAllocator>
struct move_baseGoal_
{
  typedef move_baseGoal_<ContainerAllocator> Type;

  move_baseGoal_()
    : location()  {
    }
  move_baseGoal_(const ContainerAllocator& _alloc)
    : location(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Point_<ContainerAllocator>  _location_type;
  _location_type location;




  typedef boost::shared_ptr< ::robot_actions::move_baseGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_actions::move_baseGoal_<ContainerAllocator> const> ConstPtr;

}; // struct move_baseGoal_

typedef ::robot_actions::move_baseGoal_<std::allocator<void> > move_baseGoal;

typedef boost::shared_ptr< ::robot_actions::move_baseGoal > move_baseGoalPtr;
typedef boost::shared_ptr< ::robot_actions::move_baseGoal const> move_baseGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_actions::move_baseGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_actions::move_baseGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace robot_actions

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'robot_actions': ['/home/bepis/Final_Build/devel/share/robot_actions/msg'], 'actionlib_msgs': ['/opt/ros/kinetic/share/actionlib_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::robot_actions::move_baseGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_actions::move_baseGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_actions::move_baseGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_actions::move_baseGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_actions::move_baseGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_actions::move_baseGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_actions::move_baseGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "68ff00ebc14ac99f5a5137e25226d94e";
  }

  static const char* value(const ::robot_actions::move_baseGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x68ff00ebc14ac99fULL;
  static const uint64_t static_value2 = 0x5a5137e25226d94eULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_actions::move_baseGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_actions/move_baseGoal";
  }

  static const char* value(const ::robot_actions::move_baseGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_actions::move_baseGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n\
#goal def\n\
geometry_msgs/Point location\n\
\n\
================================================================================\n\
MSG: geometry_msgs/Point\n\
# This contains the position of a point in free space\n\
float64 x\n\
float64 y\n\
float64 z\n\
";
  }

  static const char* value(const ::robot_actions::move_baseGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_actions::move_baseGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.location);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct move_baseGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_actions::move_baseGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_actions::move_baseGoal_<ContainerAllocator>& v)
  {
    s << indent << "location: ";
    s << std::endl;
    Printer< ::geometry_msgs::Point_<ContainerAllocator> >::stream(s, indent + "  ", v.location);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_ACTIONS_MESSAGE_MOVE_BASEGOAL_H
