(cl:defpackage robot_actions-msg
  (:use )
  (:export
   "<MOVE_BASEACTION>"
   "MOVE_BASEACTION"
   "<MOVE_BASEACTIONFEEDBACK>"
   "MOVE_BASEACTIONFEEDBACK"
   "<MOVE_BASEACTIONGOAL>"
   "MOVE_BASEACTIONGOAL"
   "<MOVE_BASEACTIONRESULT>"
   "MOVE_BASEACTIONRESULT"
   "<MOVE_BASEFEEDBACK>"
   "MOVE_BASEFEEDBACK"
   "<MOVE_BASEGOAL>"
   "MOVE_BASEGOAL"
   "<MOVE_BASERESULT>"
   "MOVE_BASERESULT"
  ))

