; Auto-generated. Do not edit!


(cl:in-package robot_actions-msg)


;//! \htmlinclude move_baseFeedback.msg.html

(cl:defclass <move_baseFeedback> (roslisp-msg-protocol:ros-message)
  ((location
    :reader location
    :initarg :location
    :type geometry_msgs-msg:Point
    :initform (cl:make-instance 'geometry_msgs-msg:Point)))
)

(cl:defclass move_baseFeedback (<move_baseFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <move_baseFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'move_baseFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name robot_actions-msg:<move_baseFeedback> is deprecated: use robot_actions-msg:move_baseFeedback instead.")))

(cl:ensure-generic-function 'location-val :lambda-list '(m))
(cl:defmethod location-val ((m <move_baseFeedback>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader robot_actions-msg:location-val is deprecated.  Use robot_actions-msg:location instead.")
  (location m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <move_baseFeedback>) ostream)
  "Serializes a message object of type '<move_baseFeedback>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'location) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <move_baseFeedback>) istream)
  "Deserializes a message object of type '<move_baseFeedback>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'location) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<move_baseFeedback>)))
  "Returns string type for a message object of type '<move_baseFeedback>"
  "robot_actions/move_baseFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'move_baseFeedback)))
  "Returns string type for a message object of type 'move_baseFeedback"
  "robot_actions/move_baseFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<move_baseFeedback>)))
  "Returns md5sum for a message object of type '<move_baseFeedback>"
  "68ff00ebc14ac99f5a5137e25226d94e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'move_baseFeedback)))
  "Returns md5sum for a message object of type 'move_baseFeedback"
  "68ff00ebc14ac99f5a5137e25226d94e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<move_baseFeedback>)))
  "Returns full string definition for message of type '<move_baseFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%geometry_msgs/Point location~%~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'move_baseFeedback)))
  "Returns full string definition for message of type 'move_baseFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%#feedback~%geometry_msgs/Point location~%~%~%================================================================================~%MSG: geometry_msgs/Point~%# This contains the position of a point in free space~%float64 x~%float64 y~%float64 z~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <move_baseFeedback>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'location))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <move_baseFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'move_baseFeedback
    (cl:cons ':location (location msg))
))
